# boilerplate
FROM kilianciuffolo/node:__VERSION__
MAINTAINER me@nailik.org

ENV DEBIAN_FRONTEND noninteractive

# pkgs
RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y -q \
    ssh \
    awscli \
    libpng-dev \
    && \
  apt-get clean autoclean && \
  apt-get autoremove -y && \
  rm -rf /var/lib/{apt,dpkg,cache,log}/
